# Generated by Django 4.2.5 on 2023-11-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='lga',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='locality',
            new_name='whatsapp',
        ),
    ]
