# Generated by Django 4.2.5 on 2023-11-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_city_address_lga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='lga',
        ),
        migrations.AlterField(
            model_name='address',
            name='whatsapp',
            field=models.CharField(max_length=150, verbose_name='WhatsApp Number'),
        ),
    ]
