# Generated by Django 5.2.6 on 2025-09-29 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_category_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='category',
            name='temp_image',
            field=models.ImageField(blank=True, null=True, upload_to='tmp'),
        ),
        migrations.AddField(
            model_name='product',
            name='temp_image',
            field=models.ImageField(blank=True, null=True, upload_to='tmp'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Category Image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Product Categoy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Product Image URL'),
        ),
    ]
